<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KSR" failures="1" tests="9" name="Test" time="19.903" errors="0" timestamp="2022-08-03T08:10:57 IST">
  <testcase classname="TestNgPractice.Priority_Example_Annotation_order" name="test" time="0.005"/>
  <testcase classname="TestNgPractice.Priority_Example_Annotation_order" name="test2" time="0.002"/>
  <testcase classname="TestNgPractice.Priority_Example_Annotation_order" name="test3" time="0.001"/>
  <testcase classname="TestNgPractice.Assertions" name="SoftAssert" time="0.02">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [11] but found [10]
at TestNgPractice.Assertions.SoftAssert(Assertions.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- SoftAssert -->
  <testcase classname="TestNgPractice.Priority_Example_Annotation_order" name="test4" time="0.003"/>
  <testcase classname="TestNgPractice.Priority_Example_Annotation_order" name="test5" time="0.002"/>
  <testcase classname="TestNgPractice.priorityExaple" name="googleTittle" time="2.498"/>
  <testcase classname="TestNgPractice.priorityExaple" name="zflipkartTittle" time="1.722"/>
  <testcase classname="TestNgPractice.Annotations_Usage" name="ordeofannotation" time="13.579"/>
</testsuite> <!-- Test -->
